import * as ChartJs from "https://cdn.jsdelivr.net/npm/chart.js@4.5.1/+esm";
const { Chart, registerables } = ChartJs;
Chart.register(...registerables);
import { countries } from '../data/countries.js';
import { userName, totalMoney, country, language, currency, trackerIn, trackerOut } from '../data/user-data.js';
import { dash } from './dashbourd.js';
import { trans } from './transactions.js'
import { repo } from './report.js'
import { totalIn, totalOut, totalAll } from "./calculations.js";
//// html elements ////
// html elements that contain the the pages name
const dashName = document.querySelector('.page1');//dashbourd
const transName = document.querySelector('.page2');//transactions
const repoName = document.querySelector('.page3');//reports
const sitName = document.querySelector('.page4');//sittings
const helloName = document.querySelector('.hello-div');//مرحبا hello and
const nameName = document.querySelector('.user-name');
// the html will be generated by JS in these elements
const bodyElement = document.querySelector('.main-section');
const indeElement = document.querySelector('.indecators');
//dashbourd link
const dashElement = document.querySelector('.dashbourd-div');
//
const transElement = document.querySelector('.transactions-div');
//
const repoElement = document.querySelector('.report-div');
//
const sitElement = document.querySelector('.sittings-div');
///// the static part/////
nameName.innerHTML = userName;
countries.forEach((coun) => {
  if (coun.code = country) {
    document.querySelector('.country-div').innerHTML = `<span class="fi fi-${coun.code}"></span>`
  }
});
if (language === 'sa') {
  dashName.innerHTML = 'وحده التحكم';
  transName.innerHTML = 'المعملات';
  repoName.innerHTML = 'التقارير';
  sitName.innerHTML = 'الاعدادات';
  helloName.innerHTML = 'مرحباً /';
} else if (language === 'us') {
  dashName.innerHTML = 'Dashbourd';
  transName.innerHTML = 'transactions';
  repoName.innerHTML = 'Reports';
  sitName.innerHTML = 'Sittings';
  helloName.innerHTML = 'welcome /';
};
// switcher
let page = 0;
function switchPage(newPage) {
  page = newPage;
  thePage();
}
// dashbourd
dashElement.addEventListener('click', () => {
  switchPage(0);
});
// transactions
transElement.addEventListener('click', () => {
  switchPage(1)
});
// reports 
repoElement.addEventListener('click', () => {
  switchPage(2)
});
thePage();
function thePage() {
  if (page === 0) {
    dash(language, totalMoney, currency, bodyElement, indeElement, trackerIn, trackerOut, totalAll);
  } else if (page === 1) {
    trans(bodyElement, indeElement, trackerIn, trackerOut, language, currency, totalIn, totalOut, totalAll, totalMoney);
  } else if (page === 2) {
    repo(bodyElement, indeElement, Chart, language, trackerIn, trackerOut, totalIn, totalOut);
  } else if (page === 3) {
    sitt();
  }
};
